### ISSUE TITLE
no suitable method found for pixelSearch

### ISSUE THREAD

**Issue by danrahn** [Javauto/javauto-core#4]
The pixelSearch method never works, since it cannot find the base implementation:

```
error: no suitable method found for pixelSearch(int,int,int,int,int,int)
    method ex.pixelSearch(int,int,int,int,int) is not applicable
      (actual and formal argument lists differ in length)
    method ex.pixelSearch(int) is not applicable
      (actual and formal argument lists differ in length)
```

This occurs because of `Create.getFunction()`'s processing method of checking to see if the line is of the form `public|private xxxx {` ([lines 1157-1160](https://github.com/Javauto/javauto-core/blob/master/src/main/java/com/automation/javauto/parser/Create.java#L1157)), and `pixelSearch`'s base method ([line 2085](https://github.com/Javauto/javauto-core/blob/master/src/main/java/com/automation/javauto/Javauto.java#L2085) in Javaout.java) splits the method declaration, having `int speed) {` on a new line. This issue is easily fixed by keeping the declaration on a single line, or changing the parsing method in `getFunctions()` to be more robust.

**Comment by ohtejera** [comment]
Good catch @danrahn !

Thank you.
