### ISSUE TITLE
[Feature] Graphic "script" editor

### ISSUE THREAD

**Issue by Pyeroh** [Javauto/javauto-core#5]
First of all, is this project still active ? And if not, is it possible to use it as a library in another one ?

Then, I suggest to create, like the Javauto-helper, a module to allow any 'non-familiar with code' user to create simple scripts.

If the project is not active anymore, I'll take it on my own, and I may release it when it's done.

**Comment by ohtejera** [comment]
Hi Pyeroh, 

The project still alive and also you can use this project in another project. 

Here I see two options: 

**1)** Create new project for your Javauto-Script-Editor into the [Javauto](https://github.com/Javauto) organization account 

**2)** Create a separate project that use Javauto-core as "dependency"

Please let me know your thoughts about this.
Best regards.

**Comment by Pyeroh** [comment]
Hi ! Thanks for your answer !
I'm working on other projects at the moment, but I think I'll create a separate project. 
However, you'll be kept informed about the creation of this project!

Best regards

**Comment by ohtejera** [comment]
Great!  Thank you.
